# Generated by Django 4.1.2 on 2022-10-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icdl.basemodule')),
            ],
        ),
    ]
