# Generated by Django 4.1.2 on 2022-10-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0002_basemode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemode',
            old_name='user_id',
            new_name='base',
        ),
    ]
