# Generated by Django 4.1.2 on 2022-10-06 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0003_rename_user_id_basemode_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemode',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
