# Generated by Django 4.1.2 on 2022-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0004_basemode_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemode',
            name='base',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
