# Generated by Django 4.1.2 on 2022-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0005_alter_basemode_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemode',
            old_name='base',
            new_name='base_id',
        ),
        migrations.AlterField(
            model_name='basemode',
            name='response_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
