# Generated by Django 4.1.2 on 2022-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0006_rename_base_basemode_base_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemode',
            name='base_id',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
