# Generated by Django 4.1.2 on 2022-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0007_alter_basemode_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemode',
            name='base_id',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
