# Generated by Django 4.1.2 on 2022-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0008_alter_basemode_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.BigIntegerField(max_length=10)),
                ('response', models.CharField(max_length=50)),
                ('response_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
