# Generated by Django 4.1.2 on 2022-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdl', '0009_intermediatemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemode',
            name='base_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='intermediatemode',
            name='int_id',
            field=models.BigIntegerField(),
        ),
    ]
